USE People

CREATE TABLE Users(
	Id BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Username VARCHAR(30) NOT NULL,
	[Password] VARCHAR(26) NOT NULL,
	ProfilePicture VARBINARY(MAX) NULL,
	LastLoginTime DATETIME2 NULL,
	IsDeleted VARCHAR NULL
)

INSERT INTO Users (Username, [Password],[ProfilePicture],[LastLoginTime],[IsDeleted]) VALUES
('Pesho', '123', NULL, NULL, NULL),
('Pesho', '123', NULL, NULL, NULL),
('Pesho', '123', NULL, NULL, NULL),
('Pesho', '123', NULL, NULL, NULL),
('Pesho', '123', NULL, NULL, NULL)


ALTER TABLE Users
DROP CONSTRAINT [PK__Users__3214EC077ED23507]

ALTER TABLE Users
ADD CONSTRAINT CK_PasswordIsAtLeast5symbol CHECK (LEN([Password]) > 5)

ALTER TABLE Users
ADD CONSTRAINT PK_IdUsername PRIMARY KEY(Id, Username)      

ALTER TABLE Users 
ADD CONSTRAINT DF_LastLoginTime DEFAULT GETDATE() FOR LastLoginTime


ALTER TABLE Users
DROP CONSTRAINT PK_IdUsername

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY(Id)  

ALTER TABLE Users
ADD CONSTRAINT CK_IdIsAtLeast3symbol CHECK (LEN(Id) > 3)

